name: Release Workflow test
on:
  release:
    types:
      - created
      
jobs:
  Check-new-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run build
        run: echo "Building release ${{ github.event.release.tag_name }}"
